do not override storage driver for local build
For compatibility with podman, use the default storage driver for a
local build.  When podman is configured to use overlay, it cannot
see or prune vfs images, even when you specify --storage-driver=vfs:

    % podman --storage-driver=vfs image prune
    Error: database storage graph driver "overlay" does not match our
    storage graph driver "vfs": database configuration mismatch

Because buildah does not offer a prune command, this is very
annoying - the caches grows and grows but the tooling provides no
way to prune it.  Therefore it is better to just use the same
storage driver as podman (overlay).

Also add a message that prints whether the script is invoking
buildah locally or in a container.